/* ============ Biblioteca de drills (50) ============
   cat: fw (fairways/driving) · gir (approach/hierros) · ud (up&down/juego corto) · putt */

const DRILL_CATS = [
  { id: 'fw', label: 'Fairways', art: 'driving' },
  { id: 'gir', label: 'GIR', art: 'approach' },
  { id: 'ud', label: 'Up & Down', art: 'short' },
  { id: 'putt', label: 'Putts', art: 'putting' },
];

const DRILL_LIBRARY = [
  // ---------- FAIRWAYS / DRIVING (13) ----------
  { cat: 'fw', name: 'Gate de salida', desc: 'Dos palos formando un pasillo hacia el objetivo. Trabaja tu línea de salida sin pensar en distancia.', dose: '3 × 10 bolas', metric: '≥ 7/10 por el pasillo', steps: ["Pon dos palos en el piso formando un pasillo de ~1 m apuntando al objetivo.", "Coloca la bola en el centro del pasillo.", "Pega buscando que la bola salga por el pasillo, sin pensar en distancia."] },
  { cat: 'fw', name: 'Pies juntos', desc: 'Pega drives con los pies casi juntos: encuentras el centro de la cara y suavizas el tempo.', dose: '2 × 10', metric: 'Contacto sólido 8/10', steps: ["Junta los pies casi tocándose.", "Haz swings al 70% buscando el centro de la cara.", "Si pierdes el equilibrio, suaviza el tempo."] },
  { cat: 'fw', name: '9 ventanas', desc: 'Combina 3 alturas × 3 curvas (draw / recto / fade). Domina tu cara y tu path.', dose: '9 bolas', metric: '6/9 ventanas', steps: ["Elige 3 alturas (baja/media/alta) y 3 curvas (draw/recta/fade).", "Pega una bola por cada combinación: 9 en total.", "Anota cuáles lograste y repite las que fallaste."] },
  { cat: 'fw', name: 'Step drill', desc: 'Da un paso con el pie de adelante al iniciar la bajada: sientes la secuencia y el peso.', dose: '15 swings', metric: 'Secuencia fluida', steps: ["Arranca con los pies juntos.", "Al bajar el palo, da un paso hacia el objetivo con el pie delantero.", "Siente el peso pasar al lado delantero antes de impactar."] },
  { cat: 'fw', name: 'Headcover afuera', desc: 'Pon el headcover por fuera de la bola; si lo golpeas, vienes "por fuera". Corrige el slice.', dose: '20 swings', metric: 'Sin tocarlo', steps: ["Coloca un headcover ~10 cm por fuera de la bola.", "Haz el swing sin tocarlo.", "Si lo golpeas, vienes \"por fuera\": baja más por dentro."] },
  { cat: 'fw', name: 'Toalla en las axilas', desc: 'Una toalla bajo ambos brazos mantiene la conexión cuerpo-brazos.', dose: '2 × 8', metric: 'No se cae', steps: ["Pon una toalla bajo ambas axilas.", "Haz swings de 3/4 sin que se caiga.", "Siente la conexión brazos-cuerpo en todo el giro."] },
  { cat: 'fw', name: 'Tempo 3:1', desc: 'Cuenta "uno-dos-tres" al subir y "uno" al bajar. Ritmo constante.', dose: '15 bolas', metric: 'Mismo tempo', steps: ["Cuenta \"uno-dos-tres\" al subir el palo.", "Cuenta \"uno\" en la bajada (3 veces más rápida).", "Repite el mismo conteo en cada bola."] },
  { cat: 'fw', name: 'Pausa arriba', desc: 'Haz una pausa de 1 seg en el tope del backswing para frenar el overswing.', dose: '12 bolas', metric: 'Backswing controlado', steps: ["Sube a tu tope de backswing.", "Haz una pausa de 1 segundo arriba.", "Inicia la bajada sin prisa; elimina el sobre-giro."] },
  { cat: 'fw', name: 'Driver vs Madera 3', desc: 'Alterna y compara tu dispersión real. Aprende cuándo el driver no paga.', dose: '5 + 5', metric: 'M3 < 60% de la dispersión del driver', steps: ["Pega 5 drives a una calle imaginaria y marca dónde caen.", "Pega 5 maderas 3 a la misma calle.", "Compara la dispersión y decide cuál te conviene."] },
  { cat: 'fw', name: '14 fairways', desc: 'Simula las 14 salidas de una ronda a fairways imaginarias, cambiando objetivo cada bola.', dose: '14 bolas', metric: '≥ 9/14', steps: ["Imagina las 14 salidas de una ronda.", "Cambia de objetivo en cada bola (izq/centro/der).", "Cuenta cuántas \"fairways\" hubieras pegado."] },
  { cat: 'fw', name: 'Varilla de start line', desc: 'Una varilla 2 m delante marca tu línea de salida. Valida tu dirección inicial.', dose: '10 bolas', metric: '8/10 sobre la línea', steps: ["Pon una varilla en el piso 2 m delante, en tu línea.", "Pega buscando que la bola pase sobre la varilla.", "Valida tu dirección inicial, no el resultado final."] },
  { cat: 'fw', name: 'Velocidad (overspeed)', desc: 'Swings máximos sin bola con palos de distinto peso para ganar velocidad.', dose: '3 × 5 · 2/semana', metric: '+2 mph en el mes', steps: ["Sin bola, haz swings máximos con un palo ligero y otro pesado.", "3 series de 5 swings, 2 veces por semana.", "Sube tu velocidad sin perder equilibrio."] },
  { cat: 'fw', name: 'Tee alto / tee bajo', desc: 'Cambia la altura del tee para controlar tu ángulo de ataque y el spin.', dose: '10 bolas', metric: 'Sientes la diferencia', steps: ["Pega 5 bolas con tee alto (ataque ascendente).", "Pega 5 con tee bajo (ataque más plano).", "Siente cómo cambian el vuelo y el spin."] },

  // ---------- GIR / HIERROS (12) ----------
  { cat: 'gir', name: 'Escalera de distancias', desc: 'Mismo hierro a 3 distancias distintas sin repetir. Calibra tu distancia real, no la de tu mejor golpe.', dose: '3 × 9', metric: '≥ 6/9 a < 10 m', steps: ["Elige un hierro y 3 distancias distintas.", "Pega a cada distancia alternando, sin repetir.", "Mide tu dispersión real, no tu mejor golpe."] },
  { cat: 'gir', name: 'Reloj de wedges', desc: 'Define backswing 8:00 / 9:00 / 10:00 y mide cuánto vuela cada uno. Es tu matriz de scoring.', dose: '45 min · 1/semana', metric: 'Matriz de 9 distancias', steps: ["Define backswing a las 8:00, 9:00 y 10:00.", "Pega 5 bolas por posición y mide cuánto vuela.", "Anota tu matriz de distancias por wedge."] },
  { cat: 'gir', name: 'Pin high', desc: 'Toma un palo más y pega al 80%. La mayoría falla corto, casi nunca largo.', dose: 'Próximas 2 rondas', metric: '≥ 50% pin-high o largo', steps: ["Toma un palo más de lo que crees.", "Pega al 80% de fuerza.", "Busca quedar a la altura de la bandera o pasado, nunca corto."] },
  { cat: 'gir', name: 'Divot delante', desc: 'Pon un tee 5 cm delante de la bola; tu divot debe empezar en la bola o después.', dose: '15 bolas', metric: 'Divot delante de la bola', steps: ["Pon un tee 5 cm delante de la bola.", "Pega buscando que el divot empiece en la bola o después.", "Confirma que pegas bola-primero."] },
  { cat: 'gir', name: 'Spray en la cara', desc: 'Marca la cara con spray o talco y busca impactos en el centro.', dose: '20 bolas', metric: '12/20 centradas', steps: ["Aplica spray o talco en la cara del palo.", "Pega 5 bolas y revisa dónde quedó la marca.", "Ajusta hasta centrar el impacto."] },
  { cat: 'gir', name: 'Ventana de altura', desc: 'Pega a una altura objetivo (alto / medio / bajo) para controlar trayectoria con viento.', dose: '12 bolas', metric: '3 alturas claras', steps: ["Elige una altura objetivo (alta/media/baja).", "Ajusta posición de bola y manos para lograrla.", "Pega 4 bolas por altura controlando la trayectoria."] },
  { cat: 'gir', name: 'Banderas random', desc: 'Cambia de objetivo cada bola entre 3 banderas a distintas distancias.', dose: '3 × 9', metric: 'Sin repetir objetivo', steps: ["Elige 3 banderas a distintas distancias.", "Cambia de objetivo en cada bola.", "Haz tu rutina completa antes de cada golpe."] },
  { cat: 'gir', name: 'Medio / tres cuartos', desc: 'Golpes parciales para control de distancia fino.', dose: '2 × 10', metric: 'Distancias consistentes', steps: ["Pega golpes al 50% y al 75% de swing.", "Mide cuánto vuela cada uno.", "Úsalos para afinar distancias intermedias."] },
  { cat: 'gir', name: 'Lies en pendiente', desc: 'Practica con la bola arriba/abajo de los pies para approaches reales del campo.', dose: '12 bolas', metric: 'Contacto sólido en pendiente', steps: ["Busca un lie con la bola arriba o abajo de los pies.", "Ajusta postura y agarre a la pendiente.", "Pega buscando contacto sólido y buena dirección."] },
  { cat: 'gir', name: 'Knockdown', desc: 'Golpe bajo de control: bola atrás, manos adelante, finish corto.', dose: '10 bolas', metric: 'Vuelo bajo y firme', steps: ["Bola atrás en el stance, manos adelante.", "Swing de 3/4 con finish corto.", "Busca un vuelo bajo y firme, ideal con viento."] },
  { cat: 'gir', name: 'Centro de green', desc: 'En el campo apunta SIEMPRE al centro del green y mide cuánto sube tu GIR.', dose: '2 rondas', metric: 'GIR +5%', steps: ["En cada approach apunta SIEMPRE al centro del green.", "Olvídate de atacar la bandera.", "Mide cuánto sube tu GIR en 2 rondas."] },
  { cat: 'gir', name: 'Compresión con moneda', desc: 'Una moneda detrás de la bola; tócala después de la bola, no antes.', dose: '15 bolas', metric: 'Bola primero, moneda después', steps: ["Pon una moneda 2 cm detrás de la bola.", "Pega tocando la bola primero y luego la moneda.", "Si tocas la moneda antes, pegas \"gordo\"."] },

  // ---------- UP & DOWN / JUEGO CORTO (12) ----------
  { cat: 'ud', name: 'Up & down challenge', desc: '9 posiciones aleatorias alrededor del green; juega cada una hasta embocar.', dose: '9 posiciones', metric: '≥ 5/9 up & down', steps: ["Lanza 9 bolas a posiciones aleatorias del green.", "Juega cada una hasta embocar (chip + putt).", "Cuenta cuántos up & down logras de 9."] },
  { cat: 'ud', name: 'Landing spot con toalla', desc: 'Coloca una toalla en el punto de bote ideal. El chip se controla por el bote, no por el vuelo.', dose: '3 × 8', metric: '5/8 botes en la toalla', steps: ["Coloca una toalla donde quieres que bote la bola.", "Haz el chip buscando que bote en la toalla.", "El bote manda: deja que ruede al hoyo."] },
  { cat: 'ud', name: 'Línea en el bunker', desc: 'Dibuja una línea 5 cm detrás de la bola y golpea la línea, no la bola.', dose: '20 swings + 15 bolas', metric: '10/15 fuera y en green', steps: ["Dibuja una línea 5 cm detrás de la bola en la arena.", "Golpea la arena en la línea, no la bola.", "Acelera el palo; la arena saca la bola."] },
  { cat: 'ud', name: 'Chip con 3 palos', desc: 'Mismo chip con PW, 9 y 8 según el rodado que necesitas. El bote manda.', dose: '3 × 6', metric: 'Eliges el palo correcto', steps: ["Desde el mismo lie, usa PW, 9 y 8.", "Observa cuánto vuela y cuánto rueda cada uno.", "Elige el palo según el rodado que necesitas."] },
  { cat: 'ud', name: 'Reloj del green', desc: '8 posiciones tipo reloj alrededor del green; sube y emboca.', dose: '1 vuelta', metric: '≥ 5/8 a < 1 m', steps: ["Coloca bolas en 8 puntos alrededor del green.", "Sube y emboca desde cada punto.", "Apunta a quedar a menos de 1 m."] },
  { cat: 'ud', name: 'Flop control', desc: 'Cara abierta, golpe alto y suave para pasar obstáculos cerca de bandera.', dose: '12 bolas', metric: 'Alto y blando', steps: ["Abre la cara del wedge y amplía el stance.", "Haz un swing largo y suave.", "Busca un golpe alto que caiga blando."] },
  { cat: 'ud', name: 'Rough espeso', desc: 'Salidas de lie difícil con cara abierta y golpe firme.', dose: '12 bolas', metric: '8/12 en green', steps: ["Abre un poco la cara y aprieta el agarre.", "Golpe firme y descendente.", "Acepta menos spin; calcula más rodado."] },
  { cat: 'ud', name: 'Bump and run', desc: 'Chip rodado bajo con hierro medio: el golpe más confiable bajo presión.', dose: '3 × 8', metric: 'Rodado predecible', steps: ["Usa un hierro medio (7-8) con manos adelante.", "Golpe corto tipo putt.", "Deja que la bola ruede la mayor parte del camino."] },
  { cat: 'ud', name: 'Par 18', desc: '9 chips/pitches distintos jugados a hoyo. Cuenta tu score (par 2 por hoyo).', dose: '9 hoyos', metric: 'Bajar de 20 golpes', steps: ["Juega 9 chips/pitches distintos al hoyo.", "Cada hoyo es par 2 (chip + putt).", "Suma tu score y busca bajar de 20."] },
  { cat: 'ud', name: 'Distancias de pitch', desc: '5 / 10 / 15 m con el mismo wedge, sin repetir distancia.', dose: '3 × 6', metric: '≥ 4/6 a < 2 m', steps: ["Con el mismo wedge pega a 5, 10 y 15 m.", "No repitas distancia seguida.", "Controla la distancia con el largo del backswing."] },
  { cat: 'ud', name: 'Bunker largo', desc: 'Salidas de arena de 30-40 m: más cara abierta y más giro de cuerpo.', dose: '12 bolas', metric: '8/12 en green', steps: ["Abre menos la cara que en bunker corto.", "Gira más el cuerpo para ganar distancia.", "Sigue golpeando la arena detrás de la bola."] },
  { cat: 'ud', name: 'Cuesta arriba / abajo', desc: 'Chips en pendiente para ajustar bote y rodado a la inclinación.', dose: '12 bolas', metric: 'Control en pendiente', steps: ["Alinea los hombros con la pendiente.", "Ajusta el punto de bote según suba o baje.", "Mantén el equilibrio durante todo el golpe."] },

  // ---------- PUTTS (13) ----------
  { cat: 'putt', name: 'Gate de putter', desc: 'Dos tees apenas más anchos que tu putter a 1 m. Automatiza el putt que NUNCA debes fallar.', dose: '3 × 10', metric: '≥ 9/10 embocados', steps: ["Pon dos tees apenas más anchos que tu putter a 1 m.", "Putea pasando por el gate sin tocar los tees.", "Emboca; busca 9 de 10."] },
  { cat: 'putt', name: 'Lag a círculo de 1 m', desc: 'Desde 10-15 m, deja todo dentro de un círculo de 1 m. Elimina el 3-putt.', dose: '3 × 6', metric: '≥ 5/6 dentro', steps: ["Imagina un círculo de 1 m alrededor del hoyo.", "Putea desde 10-15 m.", "Deja todas las bolas dentro del círculo."] },
  { cat: 'putt', name: 'Reloj de 1.5 m', desc: '8 putts alrededor del hoyo. Termina la vuelta sin fallar o empieza de nuevo.', dose: '2 vueltas', metric: '14/16', steps: ["Coloca 8 bolas en círculo a 1.5 m del hoyo.", "Emboca una por una.", "Si fallas, reinicia la vuelta."] },
  { cat: 'putt', name: 'Escalera de distancia', desc: '3 / 6 / 9 m controlando velocidad. Nunca dejes el putt corto.', dose: '3 × 3', metric: 'Todos pasan el hoyo', steps: ["Putea a 3, 6 y 9 m.", "Que cada bola pase el hoyo, nunca corta.", "Controla la velocidad, no la línea."] },
  { cat: 'putt', name: 'Línea de tee', desc: 'Apunta el logo de la bola a un tee 30 cm delante. Valida tu línea de salida.', dose: '10 putts', metric: '8/10 sobre el tee', steps: ["Apunta el logo de la bola a un tee 30 cm delante.", "Putea rodando el logo sobre el tee.", "Valida tu línea de salida."] },
  { cat: 'putt', name: 'Ojos cerrados', desc: 'Putts cortos con los ojos cerrados para sentir el golpe puro y el cara cuadrada.', dose: '2 × 8', metric: 'Predices dónde va', steps: ["Alinéate a un putt corto y cierra los ojos.", "Pega y predice, sin mirar, dónde quedó.", "Mejora el sentido del golpe puro."] },
  { cat: 'putt', name: 'Moneda objetivo', desc: 'Lag a una moneda en vez del hoyo para afinar la velocidad pura.', dose: '3 × 6', metric: 'A < 30 cm de la moneda', steps: ["Pon una moneda a 8-10 m como objetivo.", "Putea buscando dejar la bola sobre la moneda.", "Afinas velocidad pura sin pensar en línea."] },
  { cat: 'putt', name: 'Espejo de alineación', desc: 'Sobre un espejo de putt: ojos sobre la bola y hombros cuadrados.', dose: '5 min', metric: 'Setup repetible', steps: ["Coloca un espejo de putt en el piso.", "Ojos sobre la bola y hombros cuadrados.", "Repite el setup hasta que sea automático."] },
  { cat: 'putt', name: 'Una mano', desc: 'Putts cortos solo con la mano baja para mejorar el toque y la cara.', dose: '2 × 10', metric: 'Golpe suave', steps: ["Putts cortos solo con la mano baja.", "Siente la cara del putter cuadrada.", "Golpe suave, sin manotazo."] },
  { cat: 'putt', name: 'Doble gate', desc: 'Un gate en el putter y otro en el hoyo: controlas cara y path a la vez.', dose: '3 × 8', metric: 'Pasa ambos gates', steps: ["Pon un gate en el putter y otro junto al hoyo.", "Putea pasando por ambos gates.", "Controlas cara y línea a la vez."] },
  { cat: 'putt', name: '100 cortos', desc: '100 putts de 1 m al día. Convierte el putt corto en automático.', dose: 'Diario', metric: '95/100', steps: ["Putea 100 bolas desde 1 m.", "Misma rutina en cada una.", "Conviértelo en automático (95/100)."] },
  { cat: 'putt', name: 'Around the world', desc: 'Da la vuelta al hoyo embocando desde 1 m en cada punto del reloj.', dose: '1 vuelta', metric: 'Vuelta limpia', steps: ["Coloca bolas a 1 m en cada punto del reloj.", "Emboca dando la vuelta al hoyo.", "Si fallas, vuelves a empezar la vuelta."] },
  { cat: 'putt', name: '3 lags largos', desc: '15 / 20 / 25 m, todos a distancia de dada (gimme).', dose: '3 × 3', metric: 'Todos a < 1 m', steps: ["Putea a 15, 20 y 25 m.", "Deja cada bola a distancia de dada (< 1 m).", "Prioriza velocidad sobre línea."] },
];
