# -*- coding: utf-8 -*-
# ============================================================
# PARFECT · BANCOS DE CONTENIDO para el modo 10/día (olas semanales)
# La rutina repone bancos cada domingo. Nada se repite en TikTok.
# ============================================================

QUIZ30=[
 ('¿Cuál es el par más común en 18 hoyos?',['70','72','74'],1,'Par 72: cuatro pares 3, cuatro pares 5 y diez pares 4.'),
 ('¿Desde dónde se pierden más golpes?',['El tee','100 yardas y menos','El green'],1,'Más de la mitad de tu score se hace en 100 yardas y menos.'),
 ('¿Cuántos greens en regulación toma un HCP 36?',['1 de 3','1 de 6','1 de 12'],2,'Apenas 1 de cada 12. Ahí está la mina de golpes.'),
 ('¿Qué baja más rápido tu score?',['Driver nuevo','Clases de swing','Medir tu juego'],2,'Sin datos practicas a ciegas. Mide primero.'),
 ('¿Cuántos up & down salva un HCP 15?',['4 de 10','6 de 10','8 de 10'],0,'41%. El juego corto es la frontera del hándicap.'),
 ('¿Qué vale igual que un drive de 250?',['Un putt de 1 m','Un chip','Los dos'],2,'Todo golpe vale 1. Tu tarjeta no distingue.'),
 ('¿Cuántos 3-putts hace el amateur por ronda?',['0 a 1','1 a 2','3 o más'],1,'Entre 1 y 2. Dos golpes regalados cada ronda.'),
 ('¿Con qué palo pegas MÁS fairways?',['Driver','Madera 3','Híbrido'],1,'En hoyos cerrados la madera 3 gana score.'),
 ('¿Cuántos putts hace un scratch por ronda?',['26','30','34'],1,'30. Si haces 36, ahí tienes 6 golpes.'),
 ('¿Qué % de amateurs rompe 90?',['10%','26%','45%'],1,'Solo 1 de cada 4. Con datos, tú puedes ser ese.'),
 ('Bandera atrás del green: ¿a dónde tiras?',['A la bandera','Al frente del green','Al centro-frente'],2,'Centro-frente: el error queda debajo del hoyo.'),
 ('¿Cuál es el hoyo más difícil para el amateur?',['Par 3 largo','Par 4 con agua','Par 5 corto'],0,'El par 3 largo: green chico y palo largo.'),
 ('¿Qué mejora primero con práctica medida?',['El drive','El putt','El hierro 7'],1,'El putt responde más rápido a la práctica con meta.'),
 ('Tu wedge de 100 y cae en promedio a…',['2 m del hoyo','5 m','8 m'],2,'8 metros. Por eso el centro del green paga.'),
 ('¿Cuánto castiga el rough tu segundo tiro?',['0.2 golpes','0.5 golpes','0.8 golpes'],2,'0.8 por hoyo. El fairway es la jugada agresiva.'),
 ('¿Qué % de putts de 2 m mete el amateur?',['1 de 3','1 de 2','3 de 4'],0,'33%. Por eso el lag putt es oro.'),
 ('Después de un doble, lo correcto es…',['Atacar para recuperar','Jugar tu plan','Cambiar de swing'],1,'El campo no sabe que vienes enojado. Tu plan sí.'),
 ('¿Cuántas veces por ronda usas el driver?',['7','10','14'],2,'Hasta 14. Y el putter hasta 36. ¿Cuál practicas más?'),
 ('El "par personal" de un HCP 18 es…',['72','81','90'],2,'90: bogey golf. Persigue ESE número.'),
 ('¿Qué velocidad debe llevar un putt al hoyo?',['Fuerte y firme','Que muera en el hoyo','30 cm de pasada'],2,'Con 30 cm de pasada el hoyo se hace grande.'),
 ('¿Cuál es el error #1 en el bunker?',['Pegarle a la bola','Pegarle a la arena','Dejarla dentro'],0,'A la arena, no a la bola: 3 cm atrás.'),
 ('¿Qué % del score son golpes completos?',['80%','60%','45%'],2,'Menos de la mitad. El resto es juego corto y putt.'),
 ('Un layup inteligente se hace a…',['Lo más lejos posible','Tu yardage favorito','100 yardas exactas'],1,'A TU número. El que practicas.'),
 ('¿Cuántos golpes vale un OB del tee?',['1','2','3'],1,'Golpe y distancia: en la práctica, 2.'),
 ('¿Qué revisa primero un caddie pro?',['El viento','La bandera','El lie'],2,'El lie manda: decide qué tiro ES posible.'),
 ('¿Cuál es la meta REAL en un par 5?',['Eagle','Birdie','Evitar el doble'],2,'Evitar el doble. La ruta aburrida gana.'),
 ('¿Qué tan lejos está tu "lado corto"?',['Del lado de la bandera','Lejos de la bandera','Atrás del green'],0,'Fallar del lado de la bandera = sin green para trabajar.'),
 ('¿Cuál stat predice mejor tu hándicap?',['Fairways','GIR','Putts'],1,'GIR es el rey: greens en regulación = score.'),
 ('¿Cada cuánto deberías medir tu juego?',['Solo torneos','Una vez al mes','Cada ronda'],2,'Cada ronda cuenta una historia. Escríbela.'),
 ('El primer paso para bajar 5 golpes es…',['Palos nuevos','Conocer tu fuga #1','Más fuerza'],1,'No puedes arreglar lo que no has medido.'),
]

VF15=[
 ('El driver es el palo más importante de la bolsa', False,'El putter se usa 2× más. La tarjeta lo sabe.'),
 ('Practicar putts de 1 metro baja el score más rápido que el range', True,'4 fallos de 1 m por ronda = 4 pares regalados.'),
 ('Para romper 90 necesitas pegar drives de 250', False,'Necesitas cero dobles y bogeys tranquilos: 235 al fairway sobra.'),
 ('El green tiene zonas prohibidas antes de que tires', True,'El lado corto es cárcel: apunta al lado ANCHO.'),
 ('El amateur promedio mete el 90% de putts de 1.5 m', False,'Mete ~55%. Por eso el lag a 1 m del hoyo es oro.'),
 ('Un 7 en la tarjeta duele más que tres bogeys', True,'Tres bogeys = plan. Un 7 = ronda rota. Evita el número grande.'),
 ('Con viento en contra se pega más fuerte', False,'Más palo y swing más suave: el efecto sube menos la bola.'),
 ('Tu promedio importa más que tu mejor ronda', True,'El hándicap vive del promedio. La mejor ronda es un recuerdo.'),
 ('El chip se practica mejor en el tapete de la casa', False,'El pasto real no perdona igual: practica del lie real.'),
 ('Después de fallar el green, el par sigue vivo', True,'41% de las veces un HCP 15 lo salva. Chip + putt.'),
 ('El hoyo 1 es para atacar y arrancar con birdie', False,'El hoyo 1 es para entrar en ritmo: centro del green y a jugar.'),
 ('Anotar la ronda te hace jugar más lento', False,'3 taps por hoyo. Menos que un mensaje de WhatsApp.'),
 ('Los pros fallan más de un tercio de sus fairways', True,'PGA Tour: ~61% de fairways. Fallar es parte del plan.'),
 ('El putt cuesta arriba es más fácil que cuesta abajo', True,'De subida atacas; de bajada rezas. Deja la bola DEBAJO.'),
 ('Un buen caddie te diría dónde NO tirar', True,'Eso hace PARFECT con tus datos: te marca la zona segura.'),
]

DATOS30=[
 ('55%','de tu score','se juega en 100 yardas y menos'),
 ('41%','up & down','es lo que salva un HCP 15 en greens fallados'),
 ('36','putts por ronda','hace el amateur. El scratch: 30'),
 ('0.8','golpes de castigo','por cada drive al rough'),
 ('1/12','greens en regulación','pega un HCP 36. Y está bien'),
 ('8 m','del hoyo','cae tu wedge promedio de 100 yardas'),
 ('90','golpes','= puro bogey. El par personal del HCP 18'),
 ('2','golpes regalados','por cada 3-putt de la ronda'),
 ('26%','de los amateurs','rompe 90. Sé del club del cuarto'),
 ('33%','de putts de 2 m','mete el amateur. El lag es oro'),
 ('14','drives por ronda','vs 36 putts. ¿Qué practicas más?'),
 ('61%','de fairways','pega el PGA Tour. Fallar es normal'),
 ('+10','golpes','separan tus expectativas de tu promedio'),
 ('4','putts de 1 m','falla el amateur por ronda'),
 ('3','tiros aburridos','le ganan al tiro de héroe en el par 5'),
 ('30 cm','de pasada','la velocidad perfecta de un putt'),
 ('x2','se duplica el hoyo','cuando el putt llega muriendo'),
 ('5','golpes por ronda','cuestan 6 drives al rough'),
 ('20 min','con objetivo','valen más que 2 horas de cubetas'),
 ('0','datos','= 0 mejora. Lo que no se mide no existe'),
 ('3','taps','y tu ronda queda anotada en PARFECT'),
 ('1','tap','y la IA te dice tu fuga de golpes'),
 ('49%','GIR','y la IA ya sabe qué entrenar esta semana'),
 ('65%','de fairways','= objetivo cumplido. Siguiente prioridad'),
 ('10','rondas medidas','y tu patrón queda al descubierto'),
 ('86%','de los golfistas','no sabe cuál es su fuga #1'),
 ('4.6','promedio del par 4','desde el fairway. Desde el rough: 5.4'),
 ('1 m','del hoyo','la meta del lag putt. No el hoyo: el círculo'),
 ('7','de cada 10 dobles','empiezan con una decisión, no un mal swing'),
 ('58%','up & down','de los pros. No estás tan lejos del 41%'),
]

MEMES10=[
 ('POV: tu putt de 1 metro','de pronto mide 4 kilómetros'),
 ('POV: dijiste "la última cubeta"','hace tres cubetas'),
 ('El hoyo 1 después de calentar cero minutos','sorpresa: doble'),
 ('POV: le tiraste a la bandera escondida','saluda al bunker'),
 ('Tu swing en el range vs','tu swing con apuesta'),
 ('POV: "hoy sí rompo 90"','hoyo 3: ya vas +6'),
 ('El driver cuando más lo necesitas','modo slice activado'),
 ('POV: green de bajada, tocas la bola','la bola: nos vemos en el agua'),
 ('Tu amigo con hándicap "17"','tira 103 y culpa al campo'),
 ('POV: par salvado desde el bunker','caminas diferente al siguiente tee'),
]

RAZONES10=[
 ('3 razones por las que no bajas de 90',['Persigues el par de la tarjeta, no el tuyo','Practicas lo que ya haces bien','No sabes cuál es tu fuga #1']),
 ('3 mentiras que te dices después de una mala ronda',['"Fue mala suerte"','"El campo estaba difícil"','"Solo necesito jugar más"']),
 ('3 cosas que un caddie pro te diría',['Ese palo no es','La bandera es trampa','Tu putt decide la ronda']),
 ('3 señales de que practicas sin rumbo',['No tienes objetivo por sesión','No anotas resultados','Repites lo cómodo']),
 ('3 datos que cambian cómo juegas',['Tu % real de fairways','Tus putts por ronda','Tu proximidad con wedges']),
 ('3 hábitos de los que sí bajan hándicap',['Miden cada ronda','Practican su fuga #1','Aceptan el bogey']),
 ('3 errores del tee que pagas doble',['Driver por default','Pelear el dogleg','Ignorar el viento']),
 ('3 reglas de oro del green',['Deja la bola debajo del hoyo','30 cm de pasada','La primera lectura es la buena']),
 ('3 cosas que PARFECT hace por ti',['Anota tu ronda en 3 taps','Encuentra tu fuga con IA','Te arma la práctica exacta']),
 ('3 verdades del juego corto',['Es la mitad de tu score','Se practica del pasto real','Paga más rápido que el swing']),
]

# THEORY paramétricos (motor teoria_auto) — ola 1
TEORIAS_AUTO=[
 dict(slug='m3',lines=['EL DRIVER NO ES','OBLIGATORIO.'],sub='(la madera 3 quiere hablar)',
   f1=('vs','Fairways pegados (hoyos cerrados):',[('DRIVER','48%','RED'),('MADERA 3','63%','GREEN')]),
   f2=('contador','La diferencia por ronda:',('−3','golpes cuando eliges bien el palo del tee')),
   ins=['El tee no pide distancia.','Pide POSICIÓN.','El palo correcto es el que deja el siguiente tiro fácil.'],
   cta='PARFECT te dice tu % real por palo',shot='01-inicio.png'),
 dict(slug='agua',lines=['EL AGUA TE COBRA','ANTES DE TIRAR.'],sub='(el tiro mental existe)',
   f1=('bolitas','10 tiros con agua enfrente:',(10,6,'6 se tensan y cambian el swing')),
   f2=('vs','El mismo approach:',[('CON AGUA','5.9','RED'),('SIN AGUA','4.8','GREEN')]),
   ins=['El agua no toca tu bola.','Toca tu CABEZA.','Elige palo de sobra y swing de siempre.'],
   cta='PARFECT te enseña dónde pierdes de verdad',shot='15-diagnostico.png'),
 dict(slug='layup',lines=['EL LAYUP SE HACE','A TU NÚMERO.'],sub='(no "lo más cerca posible")',
   f1=('vs','Proximidad del 3er tiro:',[('A 40 y "cerquita"','9 m','RED'),('A TU yardage (80)','5 m','GREEN')]),
   f2=('contador','Medio green más cerca =',('−1','golpe por hoyo con layup inteligente')),
   ins=['Cerca no es mejor.','CÓMODO es mejor.','Layup a la distancia que practicas.'],
   cta='PARFECT sabe tu yardage favorito',shot='15-diagnostico.png'),
 dict(slug='viento',lines=['CON VIENTO:','MÁS PALO, MENOS EGO.'],sub='(swing suave, bola abajo)',
   f1=('vs','Viento en contra de 15 km/h:',[('MISMO PALO, DURO','+12 m error','RED'),('UN PALO MÁS, SUAVE','+4 m error','GREEN')]),
   f2=('bolitas','10 swings forzados:',(10,7,'7 pierden el centro de la cara')),
   ins=['El viento no se vence.','Se administra.','Un palo más y swing de 80%.'],
   cta='PARFECT registra tus rondas con viento',shot='11-ronda.png'),
 dict(slug='rough',lines=['DEL ROUGH:','PRIMERO SALIR.'],sub='(el héroe se queda dentro)',
   f1=('vs','Segundo tiro desde rough pesado:',[('ATACAR EL GREEN','6.1','RED'),('SALIR AL FAIRWAY','5.2','GREEN')]),
   f2=('contador','El tiro de héroe del rough:',('x2','duplica tu chance de doble o peor')),
   ins=['El rough ya te quitó medio golpe.','No le regales dos más.','Salir ES avanzar.'],
   cta='PARFECT te muestra tu patrón de errores',shot='15-diagnostico.png'),
 dict(slug='dogleg',lines=['EL DOGLEG SE JUEGA','CON EL MAPA.'],sub='(no con el ego)',
   f1=('vs','Cortar la esquina vs jugar el hoyo:',[('CORTAR','5.4','RED'),('LA RUTA','4.7','GREEN')]),
   f2=('bolitas','10 intentos de cortar:',(10,4,'solo 4 libran los árboles')),
   ins=['La línea heroica ahorra 20 metros.','Y cuesta 0.7 golpes.','Las matemáticas no aplauden: SUMAN.'],
   cta='PARFECT mide cada decisión del tee',shot='11-ronda.png'),
 dict(slug='profundidad',lines=['BANDERA ATRÁS','= FRENTE DEL GREEN.'],sub='(la profundidad es trampa)',
   f1=('bolitas','10 tiros a bandera trasera:',(10,7,'7 se quedan cortos igual')),
   f2=('vs','Score promedio del hoyo:',[('A LA BANDERA','4.9','RED'),('AL CENTRO','4.4','GREEN')]),
   ins=['La bandera de atrás es un anzuelo.','El centro del green nunca miente.','Putt de subida > chip de bajada.'],
   cta='PARFECT te enseña dónde caen TUS tiros',shot='15-diagnostico.png'),
 dict(slug='greens12',lines=['1 DE 12 GREENS.','Y ESTÁ BIEN.'],sub='(HCP 36, esto es para ti)',
   f1=('donut',('8%','GIR de un HCP 36','1 green de cada 12. Es lo NORMAL')),
   f2=('vs','Entonces, ¿de dónde salen los pares?',[('DE LLEGAR EN REG','8%','RED'),('DE CHIP + PUTT','92%','GREEN')]),
   ins=['No llegas al green en regulación.','Casi nadie llega.','Tu juego vive alrededor del green.'],
   cta='PARFECT mide tu juego corto de verdad',shot='15-diagnostico.png'),
 dict(slug='sangria',lines=['CADA 3-PUTT SON','2 GOLPES GRATIS.'],sub='(para el campo, no para ti)',
   f1=('contador','Tu ronda promedio:',('1.7','three-putts por 18 hoyos')),
   f2=('vs','Un mes de rondas (4):',[('CON 3-PUTTS','+14 golpes','RED'),('CON LAG PUTT','+4','GREEN')]),
   ins=['El 3-putt no es mala suerte.','Es un lag putt sin meta.','Círculo de 1 metro. Siempre.'],
   cta='PARFECT cuenta tus 3-putts solos',shot='11-ronda.png'),
 dict(slug='balanza',lines=['LOS BIRDIES NO','BAJAN TU HÁNDICAP.'],sub='(los dobles lo suben)',
   f1=('vs','Efecto en tu score final:',[('+1 BIRDIE','−1','GREEN'),('+2 DOBLES','+4','RED')]),
   f2=('bolitas','De tus 10 mejores rondas:',(10,8,'8 fueron rondas SIN números grandes')),
   ins=['No se rompe 90 con birdies.','Se rompe 90 sin desastres.','Caza bogeys, no héroes.'],
   cta='PARFECT te muestra dónde nacen tus dobles',shot='15-diagnostico.png'),
 dict(slug='pastel',lines=['TU SCORE VIVE EN','100 YARDAS O MENOS.'],sub='(el pastel no miente)',
   f1=('donut',('55%','de tus golpes','se dan a 100 yardas o menos del hoyo')),
   f2=('vs','¿Y tu práctica dónde vive?',[('RANGE (swing)','80%','RED'),('JUEGO CORTO','20%','GREEN')]),
   ins=['Practicas al revés.','El score está en el juego corto.','Voltea el pastel esta semana.'],
   cta='PARFECT te arma la práctica correcta',shot='06-entrenamiento.png'),
 dict(slug='promedio',lines=['TU PROMEDIO VALE MÁS','QUE TU MEJOR RONDA.'],sub='(la mejor es un recuerdo)',
   f1=('vs','¿Quién eres como golfista?',[('TU MEJOR (86)','1 vez','RED'),('TU PROMEDIO (94)','cada sábado','GREEN')]),
   f2=('contador','El hándicap se construye con:',('20','rondas. No con una tarde mágica')),
   ins=['Deja de perseguir aquella ronda.','Sube tu PISO, no tu techo.','El promedio es tu verdad.'],
   cta='PARFECT grafica tu tendencia real',shot='01-inicio.png'),
 dict(slug='lectura',lines=['LA PRIMERA LECTURA','ES LA BUENA.'],sub='(tu instinto ya leyó el green)',
   f1=('vs','Putts embocados (misma distancia):',[('RE-LEÍDO 3 VECES','28%','RED'),('PRIMERA LECTURA','41%','GREEN')]),
   f2=('bolitas','10 putts sobre-analizados:',(10,6,'6 terminan cortos: la duda frena la mano')),
   ins=['Tu primer instinto usa 10,000 greens vistos.','La duda usa miedo.','Lee, decide, suelta.'],
   cta='PARFECT registra tus putts por ronda',shot='11-ronda.png'),
 dict(slug='lag',lines=['EL LAG PUTT: TU META','ES UN CÍRCULO DE 1 M.'],sub='(no el hoyo)',
   f1=('donut',('9%','putts de 10 m embocados','ni los pros los meten: 91% NO entra')),
   f2=('vs','El segundo putt queda:',[('TIRANDO AL HOYO','2.1 m','RED'),('TIRANDO AL CÍRCULO','0.7 m','GREEN')]),
   ins=['Desde lejos no intentas meterla.','Intentas NO hacer 3.','El círculo de 1 metro es la meta.'],
   cta='PARFECT cuenta tus 3-putts',shot='15-diagnostico.png'),
 dict(slug='rutina',lines=['MISMA RUTINA,','MISMO RESULTADO.'],sub='(el putt ama la repetición)',
   f1=('vs','% embocado bajo presión:',[('RUTINA NUEVA CADA VEZ','31%','RED'),('RITUAL FIJO','47%','GREEN')]),
   f2=('bolitas','Los 10 mejores putters del mundo:',(10,10,'10 tienen rutina idéntica SIEMPRE')),
   ins=['La presión rompe lo improvisado.','No rompe lo automático.','Práctica tu ritual, no solo tu golpe.'],
   cta='PARFECT te arma drills con meta',shot='06-entrenamiento.png'),
 dict(slug='36putts',lines=['¿36 PUTTS? TU SWING','NO ES EL PROBLEMA.'],sub='(deja el range en paz)',
   f1=('donut',('40%','de tu score','fueron putts si hiciste 36 en 90')),
   f2=('vs','Dónde recuperas 5 golpes antes:',[('AFINANDO EL SWING','meses','RED'),('BAJANDO A 31 PUTTS','2 semanas','GREEN')]),
   ins=['Culpas al swing porque es ruidoso.','El putt se roba la ronda en silencio.','Mira tu tarjeta: ahí está.'],
   cta='PARFECT separa putts de golpes largos',shot='11-ronda.png'),
 dict(slug='rango-check',lines=['SI NO LO MIDES,','NO PASÓ.'],sub='(la sesión fantasma)',
   f1=('bolitas','10 sesiones de práctica sin anotar:',(10,9,'9 se olvidan en una semana')),
   f2=('vs','Un mes después:',[('SIN REGISTRO','misma fuga','RED'),('CON REGISTRO','fuga −40%','GREEN')]),
   ins=['El músculo olvida.','El dato no.','Anota la práctica como anotas la ronda.'],
   cta='PARFECT guarda tu progreso solo',shot='06-entrenamiento.png'),
 dict(slug='reset',lines=['DESPUÉS DEL DOBLE:','HOYO NUEVO.'],sub='(el campo no guarda rencor)',
   f1=('vs','El hoyo siguiente a un doble:',[('JUGADO CON CORAJE','5.6','RED'),('JUGADO EN CERO','4.6','GREEN')]),
   f2=('contador','Un doble arrastrado se convierte en:',('+4','golpes extra en los 3 hoyos siguientes')),
   ins=['El doble ya está en la tarjeta.','El siguiente tee está en blanco.','Respira. Plan. Siguiente.'],
   cta='PARFECT te enseña tus rachas',shot='15-diagnostico.png'),
]
